//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2W2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadWord
    {
        public int BadWordId { get; set; }
        public string Word { get; set; }
    }
}
