//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2W2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date_co { get; set; }
        public string Text_co { get; set; }
        public string userName { get; set; }
        public int Product_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
