//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2W2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string RegularPrice { get; set; }
        public string SalePrice { get; set; }
        public string ImageFromProduct { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<bool> IsOnSale { get; set; }
        public string LongDescription { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
