//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2W2016.AuthenticationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlgonquinCollegeUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Assignment2W2016.AuthenticationService.AlgonquinCollegeUserExtended))]
    public partial class AlgonquinCollegeUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private bool IsStudentField;
        
        private bool IsStaffField;
        
        private bool IsFacultyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsStudent {
            get {
                return this.IsStudentField;
            }
            set {
                if ((this.IsStudentField.Equals(value) != true)) {
                    this.IsStudentField = value;
                    this.RaisePropertyChanged("IsStudent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsStaff {
            get {
                return this.IsStaffField;
            }
            set {
                if ((this.IsStaffField.Equals(value) != true)) {
                    this.IsStaffField = value;
                    this.RaisePropertyChanged("IsStaff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsFaculty {
            get {
                return this.IsFacultyField;
            }
            set {
                if ((this.IsFacultyField.Equals(value) != true)) {
                    this.IsFacultyField = value;
                    this.RaisePropertyChanged("IsFaculty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlgonquinCollegeUserExtended", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AlgonquinCollegeUserExtended : Assignment2W2016.AuthenticationService.AlgonquinCollegeUser {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StudentNumber {
            get {
                return this.StudentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNumberField, value) != true)) {
                    this.StudentNumberField = value;
                    this.RaisePropertyChanged("StudentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EmployeeNumber {
            get {
                return this.EmployeeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNumberField, value) != true)) {
                    this.EmployeeNumberField = value;
                    this.RaisePropertyChanged("EmployeeNumber");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.AuthenticateServiceSoap")]
    public interface AuthenticateServiceSoap {
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        Assignment2W2016.AuthenticationService.AuthenticateUserResponse AuthenticateUser(Assignment2W2016.AuthenticationService.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserExtended", ReplyAction="*")]
        Assignment2W2016.AuthenticationService.AuthenticateUserExtendedResponse AuthenticateUserExtended(Assignment2W2016.AuthenticationService.AuthenticateUserExtendedRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        Assignment2W2016.AuthenticationService.GetUserInfoResponse GetUserInfo(Assignment2W2016.AuthenticationService.GetUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name strLastName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchUsersByLastName", ReplyAction="*")]
        Assignment2W2016.AuthenticationService.SearchUsersByLastNameResponse SearchUsersByLastName(Assignment2W2016.AuthenticationService.SearchUsersByLastNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2W2016.AuthenticationService.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(Assignment2W2016.AuthenticationService.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string strUserName, string strPassword) {
            this.strUserName = strUserName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2W2016.AuthenticationService.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(Assignment2W2016.AuthenticationService.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2W2016.AuthenticationService.AlgonquinCollegeUser AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(Assignment2W2016.AuthenticationService.AlgonquinCollegeUser AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserExtendedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserExtended", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2W2016.AuthenticationService.AuthenticateUserExtendedRequestBody Body;
        
        public AuthenticateUserExtendedRequest() {
        }
        
        public AuthenticateUserExtendedRequest(Assignment2W2016.AuthenticationService.AuthenticateUserExtendedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserExtendedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public AuthenticateUserExtendedRequestBody() {
        }
        
        public AuthenticateUserExtendedRequestBody(string strUserName, string strPassword) {
            this.strUserName = strUserName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserExtendedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserExtendedResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2W2016.AuthenticationService.AuthenticateUserExtendedResponseBody Body;
        
        public AuthenticateUserExtendedResponse() {
        }
        
        public AuthenticateUserExtendedResponse(Assignment2W2016.AuthenticationService.AuthenticateUserExtendedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserExtendedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2W2016.AuthenticationService.AlgonquinCollegeUserExtended AuthenticateUserExtendedResult;
        
        public AuthenticateUserExtendedResponseBody() {
        }
        
        public AuthenticateUserExtendedResponseBody(Assignment2W2016.AuthenticationService.AlgonquinCollegeUserExtended AuthenticateUserExtendedResult) {
            this.AuthenticateUserExtendedResult = AuthenticateUserExtendedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2W2016.AuthenticationService.GetUserInfoRequestBody Body;
        
        public GetUserInfoRequest() {
        }
        
        public GetUserInfoRequest(Assignment2W2016.AuthenticationService.GetUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strAdminUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strAdminPassword;
        
        public GetUserInfoRequestBody() {
        }
        
        public GetUserInfoRequestBody(string strUserName, string strAdminUserName, string strAdminPassword) {
            this.strUserName = strUserName;
            this.strAdminUserName = strAdminUserName;
            this.strAdminPassword = strAdminPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2W2016.AuthenticationService.GetUserInfoResponseBody Body;
        
        public GetUserInfoResponse() {
        }
        
        public GetUserInfoResponse(Assignment2W2016.AuthenticationService.GetUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2W2016.AuthenticationService.AlgonquinCollegeUser GetUserInfoResult;
        
        public GetUserInfoResponseBody() {
        }
        
        public GetUserInfoResponseBody(Assignment2W2016.AuthenticationService.AlgonquinCollegeUser GetUserInfoResult) {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUsersByLastNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUsersByLastName", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2W2016.AuthenticationService.SearchUsersByLastNameRequestBody Body;
        
        public SearchUsersByLastNameRequest() {
        }
        
        public SearchUsersByLastNameRequest(Assignment2W2016.AuthenticationService.SearchUsersByLastNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUsersByLastNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strAdminUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strAdminPassword;
        
        public SearchUsersByLastNameRequestBody() {
        }
        
        public SearchUsersByLastNameRequestBody(string strLastName, string strAdminUserName, string strAdminPassword) {
            this.strLastName = strLastName;
            this.strAdminUserName = strAdminUserName;
            this.strAdminPassword = strAdminPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUsersByLastNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUsersByLastNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2W2016.AuthenticationService.SearchUsersByLastNameResponseBody Body;
        
        public SearchUsersByLastNameResponse() {
        }
        
        public SearchUsersByLastNameResponse(Assignment2W2016.AuthenticationService.SearchUsersByLastNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUsersByLastNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2W2016.AuthenticationService.AlgonquinCollegeUser[] SearchUsersByLastNameResult;
        
        public SearchUsersByLastNameResponseBody() {
        }
        
        public SearchUsersByLastNameResponseBody(Assignment2W2016.AuthenticationService.AlgonquinCollegeUser[] SearchUsersByLastNameResult) {
            this.SearchUsersByLastNameResult = SearchUsersByLastNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticateServiceSoapChannel : Assignment2W2016.AuthenticationService.AuthenticateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateServiceSoapClient : System.ServiceModel.ClientBase<Assignment2W2016.AuthenticationService.AuthenticateServiceSoap>, Assignment2W2016.AuthenticationService.AuthenticateServiceSoap {
        
        public AuthenticateServiceSoapClient() {
        }
        
        public AuthenticateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2W2016.AuthenticationService.AuthenticateUserResponse Assignment2W2016.AuthenticationService.AuthenticateServiceSoap.AuthenticateUser(Assignment2W2016.AuthenticationService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public Assignment2W2016.AuthenticationService.AlgonquinCollegeUser AuthenticateUser(string strUserName, string strPassword) {
            Assignment2W2016.AuthenticationService.AuthenticateUserRequest inValue = new Assignment2W2016.AuthenticationService.AuthenticateUserRequest();
            inValue.Body = new Assignment2W2016.AuthenticationService.AuthenticateUserRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            Assignment2W2016.AuthenticationService.AuthenticateUserResponse retVal = ((Assignment2W2016.AuthenticationService.AuthenticateServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2W2016.AuthenticationService.AuthenticateUserExtendedResponse Assignment2W2016.AuthenticationService.AuthenticateServiceSoap.AuthenticateUserExtended(Assignment2W2016.AuthenticationService.AuthenticateUserExtendedRequest request) {
            return base.Channel.AuthenticateUserExtended(request);
        }
        
        public Assignment2W2016.AuthenticationService.AlgonquinCollegeUserExtended AuthenticateUserExtended(string strUserName, string strPassword) {
            Assignment2W2016.AuthenticationService.AuthenticateUserExtendedRequest inValue = new Assignment2W2016.AuthenticationService.AuthenticateUserExtendedRequest();
            inValue.Body = new Assignment2W2016.AuthenticationService.AuthenticateUserExtendedRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            Assignment2W2016.AuthenticationService.AuthenticateUserExtendedResponse retVal = ((Assignment2W2016.AuthenticationService.AuthenticateServiceSoap)(this)).AuthenticateUserExtended(inValue);
            return retVal.Body.AuthenticateUserExtendedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2W2016.AuthenticationService.GetUserInfoResponse Assignment2W2016.AuthenticationService.AuthenticateServiceSoap.GetUserInfo(Assignment2W2016.AuthenticationService.GetUserInfoRequest request) {
            return base.Channel.GetUserInfo(request);
        }
        
        public Assignment2W2016.AuthenticationService.AlgonquinCollegeUser GetUserInfo(string strUserName, string strAdminUserName, string strAdminPassword) {
            Assignment2W2016.AuthenticationService.GetUserInfoRequest inValue = new Assignment2W2016.AuthenticationService.GetUserInfoRequest();
            inValue.Body = new Assignment2W2016.AuthenticationService.GetUserInfoRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strAdminUserName = strAdminUserName;
            inValue.Body.strAdminPassword = strAdminPassword;
            Assignment2W2016.AuthenticationService.GetUserInfoResponse retVal = ((Assignment2W2016.AuthenticationService.AuthenticateServiceSoap)(this)).GetUserInfo(inValue);
            return retVal.Body.GetUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2W2016.AuthenticationService.SearchUsersByLastNameResponse Assignment2W2016.AuthenticationService.AuthenticateServiceSoap.SearchUsersByLastName(Assignment2W2016.AuthenticationService.SearchUsersByLastNameRequest request) {
            return base.Channel.SearchUsersByLastName(request);
        }
        
        public Assignment2W2016.AuthenticationService.AlgonquinCollegeUser[] SearchUsersByLastName(string strLastName, string strAdminUserName, string strAdminPassword) {
            Assignment2W2016.AuthenticationService.SearchUsersByLastNameRequest inValue = new Assignment2W2016.AuthenticationService.SearchUsersByLastNameRequest();
            inValue.Body = new Assignment2W2016.AuthenticationService.SearchUsersByLastNameRequestBody();
            inValue.Body.strLastName = strLastName;
            inValue.Body.strAdminUserName = strAdminUserName;
            inValue.Body.strAdminPassword = strAdminPassword;
            Assignment2W2016.AuthenticationService.SearchUsersByLastNameResponse retVal = ((Assignment2W2016.AuthenticationService.AuthenticateServiceSoap)(this)).SearchUsersByLastName(inValue);
            return retVal.Body.SearchUsersByLastNameResult;
        }
    }
}
